import '../import_helper.dart';
import 'dart:math';

class SplashScreen extends StatefulWidget {
  const SplashScreen({super.key});
    @override
      State<SplashScreen> createState() => _SplashScreenState();
      }

      class _SplashScreenState extends State<SplashScreen> with TickerProviderStateMixin {
        late AnimationController _logoCtrl, _ringCtrl, _fadeCtrl, _dotCtrl;
          late Animation<double> _logoScale, _logoOpacity, _ringScale, _ringOpacity, _textFade;

            @override
              void initState() {
                  super.initState();
                      _logoCtrl = AnimationController(vsync: this, duration: const Duration(milliseconds: 900));
                          _ringCtrl = AnimationController(vsync: this, duration: const Duration(milliseconds: 2000))..repeat();
                              _fadeCtrl = AnimationController(vsync: this, duration: const Duration(milliseconds: 600));
                                  _dotCtrl  = AnimationController(vsync: this, duration: const Duration(milliseconds: 1200))..repeat();
                                      _logoScale   = CurvedAnimation(parent: _logoCtrl, curve: Curves.elasticOut).drive(Tween(begin: 0.0, end: 1.0));
                                          _logoOpacity = CurvedAnimation(parent: _logoCtrl, curve: Curves.easeIn).drive(Tween(begin: 0.0, end: 1.0));
                                              _ringScale   = CurvedAnimation(parent: _ringCtrl, curve: Curves.easeOut).drive(Tween(begin: 0.6, end: 1.4));
                                                  _ringOpacity = CurvedAnimation(parent: _ringCtrl, curve: Curves.easeOut).drive(Tween(begin: 0.6, end: 0.0));
                                                      _textFade    = CurvedAnimation(parent: _fadeCtrl, curve: Curves.easeIn).drive(Tween(begin: 0.0, end: 1.0));
                                                          Future.delayed(const Duration(milliseconds: 200), () => _logoCtrl.forward());
                                                              Future.delayed(const Duration(milliseconds: 700), () => _fadeCtrl.forward());
                                                                  _checkAuth();
                                                                    }

                                                                      void _checkAuth() async {
                                                                          await Future.delayed(const Duration(milliseconds: 2400));
                                                                              if (!mounted) return;
                                                                                  final prefs = await SharedPreferences.getInstance();
                                                                                      final apiKey = prefs.getString('tynex_api_key');
                                                                                          Navigator.pushReplacement(context, PageRouteBuilder(
                                                                                                pageBuilder: (_, __, ___) => apiKey == null || apiKey.isEmpty ? const ApiKeySetupScreen() : const ChatScreen(),
                                                                                                      transitionDuration: const Duration(milliseconds: 500),
                                                                                                            transitionsBuilder: (_, a, __, child) => FadeTransition(opacity: a, child: child),
                                                                                                                ));
                                                                                                                  }

                                                                                                                    @override
                                                                                                                      void dispose() { _logoCtrl.dispose(); _ringCtrl.dispose(); _fadeCtrl.dispose(); _dotCtrl.dispose(); super.dispose(); }

                                                                                                                        @override
                                                                                                                          Widget build(BuildContext context) {
                                                                                                                              return Scaffold(
                                                                                                                                    backgroundColor: AppTheme.background,
                                                                                                                                          body: Stack(fit: StackFit.expand, children: [
                                                                                                                                                  const NeonOrb(color: AppTheme.primary, size: 400, alignment: Alignment(-0.6, -0.7), opacity: 0.07),
                                                                                                                                                          const NeonOrb(color: AppTheme.secondaryAccent, size: 350, alignment: Alignment(0.7, 0.6), opacity: 0.07),
                                                                                                                                                                  const ScanLine(),
                                                                                                                                                                          Center(child: Column(mainAxisAlignment: MainAxisAlignment.center, children: [
                                                                                                                                                                                    ScaleTransition(scale: _logoScale, child: FadeTransition(opacity: _logoOpacity,
                                                                                                                                                                                                child: SizedBox(width: 120, height: 120, child: Stack(alignment: Alignment.center, children: [
                                                                                                                                                                                                              AnimatedBuilder(animation: _ringCtrl, builder: (_, __) => Transform.scale(scale: _ringScale.value,
                                                                                                                                                                                                                              child: Container(width: 110, height: 110, decoration: BoxDecoration(shape: BoxShape.circle,
                                                                                                                                                                                                                                                border: Border.all(color: AppTheme.primary.withOpacity(_ringOpacity.value), width: 2))))),
                                                                                                                                                                                                                                                              Container(width: 90, height: 90, decoration: BoxDecoration(shape: BoxShape.circle,
                                                                                                                                                                                                                                                                              gradient: const LinearGradient(colors: [Color(0xFF0D1A2E), Color(0xFF060D1A)], begin: Alignment.topLeft, end: Alignment.bottomRight),
                                                                                                                                                                                                                                                                                              border: Border.all(color: AppTheme.primary.withOpacity(0.6), width: 1.5),
                                                                                                                                                                                                                                                                                                              boxShadow: const [AppTheme.neonGlow, AppTheme.purpleGlow])),
                                                                                                                                                                                                                                                                                                                            ShaderMask(blendMode: BlendMode.srcIn,
                                                                                                                                                                                                                                                                                                                                            shaderCallback: (b) => AppTheme.primaryGradient.createShader(Rect.fromLTWH(0, 0, b.width, b.height)),
                                                                                                                                                                                                                                                                                                                                                            child: Text("T", style: GoogleFonts.orbitron(fontSize: 42, fontWeight: FontWeight.w900))),
                                                                                                                                                                                                                                                                                                                                                                        ])))),
                                                                                                                                                                                                                                                                                                                                                                                  const SizedBox(height: 32),
                                                                                                                                                                                                                                                                                                                                                                                            FadeTransition(opacity: _textFade, child: Column(children: [
                                                                                                                                                                                                                                                                                                                                                                                                        RichText(text: TextSpan(children: [
                                                                                                                                                                                                                                                                                                                                                                                                                      TextSpan(text: "TYNEX", style: GoogleFonts.orbitron(fontSize: 32, fontWeight: FontWeight.w900, color: Colors.white, letterSpacing: 6)),
                                                                                                                                                                                                                                                                                                                                                                                                                                    TextSpan(text: " AI",  style: GoogleFonts.orbitron(fontSize: 32, fontWeight: FontWeight.w900, color: AppTheme.primary, letterSpacing: 6)),
                                                                                                                                                                                                                                                                                                                                                                                                                                                ])),
                                                                                                                                                                                                                                                                                                                                                                                                                                                            const SizedBox(height: 10),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        Container(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      padding: const EdgeInsets.symmetric(horizontal: 14, vertical: 5),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    decoration: BoxDecoration(border: Border.all(color: AppTheme.primary.withOpacity(0.3)), borderRadius: BorderRadius.circular(20), color: AppTheme.primary.withOpacity(0.05)),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  child: Text("PREMIUM AI AGENT", style: GoogleFonts.orbitron(fontSize: 9, color: AppTheme.primary, letterSpacing: 4, fontWeight: FontWeight.w700)),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ])),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  const SizedBox(height: 60),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            FadeTransition(opacity: _textFade, child: AnimatedBuilder(animation: _dotCtrl,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        builder: (_, __) => Row(mainAxisAlignment: MainAxisAlignment.center,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      children: List.generate(3, (i) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      final t = (_dotCtrl.value - i * 0.15).clamp(0.0, 1.0);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      final opacity = (sin(t * pi)).clamp(0.2, 1.0);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      return Container(margin: const EdgeInsets.symmetric(horizontal: 5), width: 6, height: 6,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        decoration: BoxDecoration(shape: BoxShape.circle, color: AppTheme.primary.withOpacity(opacity),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            boxShadow: [BoxShadow(color: AppTheme.primary.withOpacity(opacity * 0.5), blurRadius: 6)]));
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          })))),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ])),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          Positioned(bottom: 32, left: 0, right: 0,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    child: FadeTransition(opacity: _textFade,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                child: Text("v1.0.0", textAlign: TextAlign.center, style: GoogleFonts.jetBrainsMono(fontSize: 10, color: AppTheme.textMuted, letterSpacing: 2)))),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ]),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }